import { Inter,Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
Toaster
const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "MeetMate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Toaster/>
        {children} </body>
      
    </html>
  );
}
